### PR TITLE
Policy: Fix description and rename file

### PR DESCRIPTION
**Pull request by danrabbit**
It seems like polkit doesn't like ampersands:

## BEFORE
Screenshot from 2020-04-09 11 46 32@2x

## AFTER
Screenshot from 2020-04-09 12 08 10@2x

### CODE REVIEW

**Comment by cassidyjames** [comment]
Huh. Is it just not being escaped properly somewhere? It would be nice to be able to consistently call it "Screen Time & Limits" imho since it's more similar to all other plugs like "Language & Region", "Security & Privacy", "Mouse & Touchpad", and "Date & Time". :confused:

**Comment by cassidyjames** [comment]
Okay, after poking at this, I can't get any representation of an ampersand (including `&#038;`) to work correctly. So `and` it is. :)

**Comment by cassidyjames** [comment]
It might also be worth double-checking this with another policykit dialog implementation, i.e. on GNOME Shell just to see if it's our dialog's fault or not.

**Comment by 4jNsY6fCVqZv** [comment]
Asked out of curiosity: How do the other plugs you mentioned solve this?

**Pull request merged**
